interTwin-eu/itwinai

- .github/linters/mlc_config.json
- AUTHORS.md
- CONTRIBUTING.md
- README.md
Add emails of maintainers and fix links
> Housekeeping

- .github/workflows/sqaaas.yml
Make the SQAaaS GH action adapt on the branch on which it is executed
> Sqaaas code

- pyproject.toml
- src/itwinai/components.py
- use-cases/mnist/torch/pipeline.yaml
Add named steps to the pipeline
> Named steps pipe

- .github/workflows/sqaaas.yml
- README.md
The SQAaaS badge (for source code) is dynamically updated in accordance with the progress of the quality assessment.
---
> Add SQAaaS dynamic badge for dev branch

- README.md
The SQAaaS badge (for source code) is dynamically updated in accordance with the progress of the quality assessment. 
---
> Add SQAaaS dynamic badge for main branch

- README.md
> fix links in the docs

- .github/workflows/sqaaas.yml
- pyproject.toml
- tests/use-cases/test_cyclones.py
---
Working workflow validation using unit testing criterion (QC.Uni) in SQAaaS
> Unit test 4 dev

- tutorials/distributed-ml/torch-tutorial-0-basics/README.md
- tutorials/distributed-ml/torch-tutorial-0-basics/train.py
Add some examples on running distributed ml in interactive mode
> Interactive distrib ml

- .github/workflows/lint.yml
- .github/workflows/pages.yml
Bring changes on main into dev
> Merge main

- README.md
- env-files/itwinai-installer.sh
- env-files/tensorflow/generic_tf.sh
- env-files/torch/generic_torch.sh
> Simplified install for users

- docs/cyclones_doc.rst
- docs/getting_started_with_itwinai.rst
- docs/index.rst
- docs/virgo_doc.rst
> updating doc pages

- docs/conf.py
- docs/cyclones_doc.rst
- docs/getting_started_with_itwinai.rst
- docs/index.rst
- docs/virgo_doc.rst
> Docs changes

- pyproject.toml
- src/itwinai/loggers.py
- src/itwinai/torch/config.py
- src/itwinai/torch/trainer.py
- tests/test_loggers.py
- tutorials/distributed-ml/torch-tutorial-0-basics/train.py
- use-cases/virgo/config.yaml
- use-cases/virgo/train.py
- use-cases/virgo/trainer.py
Fix problem with Virgo distributed dataloader and refactor itwinai core
> Patch Virgo dataloader and refactor

- src/itwinai/torch/config.py
- src/itwinai/torch/trainer.py
- tests/torch/test_config.py
- use-cases/mnist/torch/config.yaml
Improve torch trainer adding optimizer selection from training configuration
> ADD optimizer selection

- pyproject.toml
- src/itwinai/cli.py
- src/itwinai/loggers.py
- src/itwinai/torch/config.py
- src/itwinai/torch/trainer.py
- tutorials/distributed-ml/torch-tutorial-2-trainer-class/README.md
- tutorials/distributed-ml/torch-tutorial-2-trainer-class/train.py
- tutorials/distributed-ml/torch-tutorial-2-trainer/train.py
Add tutorial on itwinai `TorchTrainer`, plus some refactoring
> Torch trainer tutorial

- use-cases/3dgan/Dockerfile
- use-cases/3dgan/__init__.py
- use-cases/3dgan/config.yaml
- use-cases/3dgan/dataloader.py
- use-cases/3dgan/interLink/3dgan-inference-cpu.yaml
- use-cases/3dgan/interLink/3dgan-inference.yaml
- use-cases/3dgan/interLink/3dgan-train.yaml
- use-cases/3dgan/interLink/README.md
update 3dgan's interLink pods for training and inference
> UPDATE interLink pods for 3DGAN

- env-files/tensorflow/create_container_env.sh
- env-files/tensorflow/generic_tf.sh
- env-files/torch/create_container_env.sh
- env-files/torch/generic_torch.sh
- pyproject.toml
Add explicit installation for Prov4ML before itwinai to account for different HW arch
> Fix prov4ml extras

- .github/linters/.isort.cfg
- .github/workflows/lint.yml
- .isort.cfg
- pyproject.toml
- src/itwinai/cli.py
- src/itwinai/loggers.py
- src/itwinai/torch/config.py
- src/itwinai/torch/distributed.py
- src/itwinai/torch/inference.py
- src/itwinai/torch/mlflow.py
- src/itwinai/torch/models/mnist.py
- src/itwinai/torch/reproducibility.py
- src/itwinai/torch/trainer.py
- src/itwinai/torch/type.py
- tutorials/distributed-ml/torch-scaling-test/itwinai_trainer.py
- tutorials/distributed-ml/torch-tutorial-GAN/README.md
- tutorials/distributed-ml/torch-tutorial-GAN/simpleGAN.py
- use-cases/3dgan/README.md
Small stylistic changes to make code and tutorials more readable.
---
> Stylistic changes

- env-files/torch/Dockerfile
- env-files/torch/create_container_env.sh
> Fix torch container build

- AUTHORS.md
- CITATION.cff
- docs/conf.py
- env-files/itwinai-installer.sh
- env-files/tensorflow/generic_tf.sh
- env-files/torch/generic_torch.sh
Update user installation scripts and cleanup
> 224 break when env installation fails on user installation script

- .github/workflows/lint.yml
- .vscode/extensions.json
- src/itwinai/cli.py
- src/itwinai/tests/__init__.py
- src/itwinai/tests/dummy_components.py
- src/itwinai/tests/exceptions.py
- src/itwinai/tests/sanity_check.py
Add import sanity checks to easily test installation of itwinai and its dependencies
> ADD import sanity checks

- .github/workflows/sqaaas.yml
Bump to image of SQAaaS action to sqaaas-micromamba:1.5.3-1-rc.8
---
fixes #158
> Bump to image of SQAaaS action to sqaaas-micromamba:1.5.3-1-rc.8

- use-cases/eurac/hpo.py
- use-cases/eurac/slurm_ray.sh
- use-cases/eurac/trainer.py
This PR fixed the issue #234. The hpo script could not run due to incompatibility with some changes made to the config.yaml file since the last test.
> Added config option to hpo script, styling

- src/itwinai/torch/distributed.py
- src/itwinai/torch/profiling/profiler.py
- use-cases/eurac/config.yaml
- use-cases/eurac/runall.sh
- use-cases/eurac/trainer.py
- use-cases/virgo/trainer.py
Fixes the bug where the scalability study does not work. Mostly consisted of silly imports and incorrect positioning of the decorator.
> Fix scalability bug

- docs/python-api/itwinai.loggers.rst
- docs/python-api/itwinai.torch.modules.rst
This PR adds the lightning logger to the API reference in the docs. 
> Added lightning logger to API reference

- docs/requirements.txt
- pyproject.toml
> Fix broken docs

- ci/pyproject.toml
A dummy mistake happened when refactoring the code base. Fixing it.
---
> Patch container CI 

- .github/workflows/lint.yml
- .readthedocs.yaml
- src/itwinai/loggers.py
- src/itwinai/parser.py
- src/itwinai/torch/config.py
Improve the readability of errors when using the itwinai config parser, for instance when executing a pipeline from configuration file.
---
Closes #259
> Add Path in loggers and clearer error handling

- ci/dagger.json
- env-files/torch/Dockerfile
> Fix tests in container CI

- .github/workflows/sqaaas.yml
> sqaaas unit tests failing

- use-cases/virgo/README.md
- use-cases/virgo/config.yaml
- use-cases/virgo/trainer.py
Updates the Virgo README with recent developments.
> Update Virgo README

- src/itwinai/torch/loggers.py
Add the possibility to skip logger finalize in lightning logger abstraction
---
> Add the possibility to skip logger finalize in lightning logger abstraction

- use-cases/eurac/config.yaml
- use-cases/eurac/data.py
- use-cases/eurac/requirements.txt
- use-cases/eurac/trainer.py
This PR updates the Eurac use case pipeline to run with the refactored version of Hython.
Among other things, it adds the possibility to train a model with a probabilistic head layer, for uncertainty estimation.
The convlstm pipeline has been removed, and it will be reintegrated in the future.
---
> update eurac use case

- .github/actions/build-container/action.yml
EGI Registry's auth keep failing. Migrating to CERN registry. 
---
> Migrate to CERN container registry

- src/itwinai/cli.py
- src/itwinai/scalability_report/plot.py
- src/itwinai/scalability_report/reports.py
- tutorials/ml-workflows/02-pipeline-configuration/tutorial_1_intermediate_workflow.rst
As mentioned in #333, the bars of the GPU plot sometimes had an unsorted x-axis and misalignment problems. This has now been fixed. 
Old plot: 
New plot: 
Sanity check with more "uniform", normal plots:
> Update bar plots for scalability report

- docs/how-it-works/hpo/explain-hpo.rst
- docs/how-it-works/hpo/images/hpo_fig_eurac.svg
- src/itwinai/cli.py
- tutorials/ml-workflows/02-pipeline-configuration/tutorial_1_intermediate_workflow.rst
This adds a function for downloading MLFlow data. See #339 for slightly more elaboration. It also adds some plots to the documentation.
> Download MLFlow Data and Add Plots to Documentation

- env-files/torch/jupyter/configure.py
> Update configure.py to fix rucio conf

- .github/workflows/pytest.yml
- src/itwinai/torch/distributed.py
- tests/loggers/test_prov4ml.py
mlflow env vars for authentication are now accessible inside ray workers.
> fixed worker access to mlflow env vars

- .github/actions/build-container/action.yml
Temp fix for the following error in Dagger workflows:
```text
ValueError: mutable default <class 'dagger.Container'> for field base_image is not allowed: use default_factory
```
---
> Patch Dagger version

- .github/workflows/pytest.yml
- docs/getting-started/plugins-list.rst
The list of plugins is updated to include the normflow plugin repository.
> Adding normflow to list of plugins in the docs

- src/itwinai/cli.py
- src/itwinai/slurm/slurm_script_builder.py
- src/itwinai/slurm/utils.py
Added pre-exec command flag to SLURM builder.
> added pre-exec flag for builder

- README.md
made logo adaptive so separate logo as in #372 is not needed anymore
> made logo light dark mode adaptive for github

- .github/workflows/container-ci.yml
- docs/getting-started/containers.rst
- docs/working-with-containers.md
- env-files/torch/jupyter/cloud.Dockerfile
- env-files/torch/jupyter/slim.Dockerfile
- env-files/torch/jupyter/start-cloud.sh
Add Dockerfile for JupyterLab container image for cloud only (no interLink offloading)
---
> Jlab cloud container image

- .gitignore
- docs/tutorials/profiling/py-spy-profiling.rst
- docs/tutorials/tutorials.rst
- src/itwinai/cli.py
- src/itwinai/slurm/slurm_script_builder.py
- src/itwinai/slurm/utils.py
- src/itwinai/torch/profiling/profiler.py
- src/itwinai/torch/profiling/py_spy_aggregation.py
- src/itwinai/torch/trainer.py
- tests/test_slurm_builder.py
- use-cases/mnist/torch/slurm_config.yaml
- `generate-py-spy-report` can now read directories as well as files
- SLURM script builder now allows multi-node use of `py-spy` with a boolean flag
- General clean-up
I will add the new documentation in a new branch I think, just so we can merge things a bit quicker
> Finalize py-spy integration

- docs/getting-started/slurm.rst
- src/itwinai/cli.py
- src/itwinai/slurm/slurm_config.yaml
- src/itwinai/slurm/slurm_constants.py
- src/itwinai/slurm/slurm_script_builder.py
- src/itwinai/slurm/utils.py
- tests/test_slurm_builder.py
- tutorials/distributed-ml/torch-scaling-test/slurm.py
- tutorials/distributed-ml/torch-scaling-test/slurm_config.yaml
- tutorials/distributed-ml/torch-tutorial-0-basics/slurm_config.yaml
- tutorials/distributed-ml/torch-tutorial-1-mnist/slurm_config.yaml
- tutorials/distributed-ml/torch-tutorial-GAN/slurm_config.yaml
- use-cases/eurac/slurm_config.yaml
- use-cases/virgo/slurm_config.yaml
---
FIx problem with `--cpus-per-gpu` on JSC juwels
**Related issue :** Fixes #415
> Patch slurm script builder for JSC

- src/itwinai/distributed.py
- src/itwinai/torch/distributed.py
Improve debug message for Ray attempting to connect to a Ray cluster (even when not wanting to use Ray). This was confusing the users, who used to see an error message on Ray not finding the cluster, thinking that the code is failing
---
> Patch needlessly worrisome debug message on Ray not finding the Ray cluster

- src/itwinai/loggers.py
- src/itwinai/torch/profiling/profiler.py
- src/itwinai/torch/trainer.py
fixes:
- racing condition leading to duplications in experiment creation
- tracking uri problem for local addresses
> Hotfixes for distributed mlflow logging

- docs/installation/hpc_modules.rst
> add mpi4py install instructions on vega

- docs/index.rst
> Add Discord to docs
